[package]
name = "bm-core"
version = "0.1.0"
edition = "2024"

[dependencies]
poem.workspace = true
poem-openapi.workspace = true
tokio.workspace = true
shuttle-poem.workspace = true
shuttle-runtime.workspace = true
